#!/bin/sh
set -eu

: "${SEVEN_DAYS_HOST:?SEVEN_DAYS_HOST is required}"
export SEVEN_DAYS_WEB_PORT="${SEVEN_DAYS_WEB_PORT:-8080}"

export FRONTEND_MAP_NATIVE_MAX_ZOOM="${FRONTEND_MAP_NATIVE_MAX_ZOOM:-4}"
export FRONTEND_MAP_TILE_SIZE="${FRONTEND_MAP_TILE_SIZE:-128}"
export FRONTEND_GAME_TIME_REFRESH_MS="${FRONTEND_GAME_TIME_REFRESH_MS:-10000}"
export FRONTEND_PLAYER_REFRESH_MS="${FRONTEND_PLAYER_REFRESH_MS:-10000}"
export FRONTEND_ACTIVITY_REFRESH_MS="${FRONTEND_ACTIVITY_REFRESH_MS:-10000}"
export FRONTEND_MAP_ENTITY_REFRESH_MS="${FRONTEND_MAP_ENTITY_REFRESH_MS:-10000}"
export FRONTEND_TRADER_EXPLORATION_REFRESH_MS="${FRONTEND_TRADER_EXPLORATION_REFRESH_MS:-5000}"
export FRONTEND_SERVER_VERSION_REFRESH_MS="${FRONTEND_SERVER_VERSION_REFRESH_MS:-60000}"
export FRONTEND_APP_VERSION_REFRESH_MS="${FRONTEND_APP_VERSION_REFRESH_MS:-60000}"
export FRONTEND_GAME_SCHEDULE_REFRESH_MS="${FRONTEND_GAME_SCHEDULE_REFRESH_MS:-60000}"
export FRONTEND_RESTART_STATUS_REFRESH_MS="${FRONTEND_RESTART_STATUS_REFRESH_MS:-5000}"
export FRONTEND_UNEXPLORED_TILE_MAX_BYTES="${FRONTEND_UNEXPLORED_TILE_MAX_BYTES:-400}"
export FRONTEND_TILE_RETRY_DELAYS_MS="${FRONTEND_TILE_RETRY_DELAYS_MS:-0,250,750,1500}"
export FRONTEND_CONFIG_RETRY_DELAYS_MS="${FRONTEND_CONFIG_RETRY_DELAYS_MS:-0,300,900}"
export FRONTEND_UNEXPLORED_TILE_REFRESH_MS="${FRONTEND_UNEXPLORED_TILE_REFRESH_MS:-5000}"
export FRONTEND_MOVING_PLAYER_MIN_SPEED_MPS="${FRONTEND_MOVING_PLAYER_MIN_SPEED_MPS:-4}"
export FRONTEND_MOVING_VEHICLE_MATCH_RADIUS="${FRONTEND_MOVING_VEHICLE_MATCH_RADIUS:-160}"
export FRONTEND_MOVING_VEHICLE_RELEASE_MS="${FRONTEND_MOVING_VEHICLE_RELEASE_MS:-20000}"

export NGINX_WORKER_CONNECTIONS="${NGINX_WORKER_CONNECTIONS:-1024}"
export NGINX_KEEPALIVE_TIMEOUT_SECONDS="${NGINX_KEEPALIVE_TIMEOUT_SECONDS:-30}"
export NGINX_TRUSTED_PROXY_CIDR="${NGINX_TRUSTED_PROXY_CIDR:-172.16.0.0/12}"
export NGINX_UPSTREAM_KEEPALIVE="${NGINX_UPSTREAM_KEEPALIVE:-8}"
export NGINX_MAP_CACHE_KEYS_ZONE_SIZE="${NGINX_MAP_CACHE_KEYS_ZONE_SIZE:-16m}"
export NGINX_MAP_CACHE_MAX_SIZE="${NGINX_MAP_CACHE_MAX_SIZE:-2g}"
export NGINX_MAP_CACHE_INACTIVE="${NGINX_MAP_CACHE_INACTIVE:-7d}"
export NGINX_MAP_TILE_CACHE_MAX_AGE_SECONDS="${NGINX_MAP_TILE_CACHE_MAX_AGE_SECONDS:-60}"
export NGINX_MAP_TILE_STALE_SECONDS="${NGINX_MAP_TILE_STALE_SECONDS:-240}"
export NGINX_STATIC_CACHE_MAX_AGE_SECONDS="${NGINX_STATIC_CACHE_MAX_AGE_SECONDS:-604800}"
export NGINX_BIOME_CACHE_MAX_AGE_SECONDS="${NGINX_BIOME_CACHE_MAX_AGE_SECONDS:-3600}"
export NGINX_MAP_API_RATE="${NGINX_MAP_API_RATE:-20r/s}"
export NGINX_PLAYER_API_RATE="${NGINX_PLAYER_API_RATE:-10r/s}"
export NGINX_CONTROL_STATUS_RATE="${NGINX_CONTROL_STATUS_RATE:-10r/s}"
export NGINX_CONTROL_ACTION_RATE="${NGINX_CONTROL_ACTION_RATE:-1r/s}"
export NGINX_MAP_TILE_RATE="${NGINX_MAP_TILE_RATE:-200r/s}"
export NGINX_MAP_API_BURST="${NGINX_MAP_API_BURST:-50}"
export NGINX_PLAYER_API_BURST="${NGINX_PLAYER_API_BURST:-30}"
export NGINX_CONTROL_STATUS_BURST="${NGINX_CONTROL_STATUS_BURST:-30}"
export NGINX_CONTROL_ACTION_BURST="${NGINX_CONTROL_ACTION_BURST:-5}"
export NGINX_MAP_TILE_BURST="${NGINX_MAP_TILE_BURST:-500}"
export NGINX_PROXY_CONNECT_TIMEOUT_SECONDS="${NGINX_PROXY_CONNECT_TIMEOUT_SECONDS:-3}"
export NGINX_MAP_API_READ_TIMEOUT_SECONDS="${NGINX_MAP_API_READ_TIMEOUT_SECONDS:-5}"
export NGINX_PRIVATE_API_READ_TIMEOUT_SECONDS="${NGINX_PRIVATE_API_READ_TIMEOUT_SECONDS:-7}"
export NGINX_MAP_TILE_READ_TIMEOUT_SECONDS="${NGINX_MAP_TILE_READ_TIMEOUT_SECONDS:-10}"
export NGINX_CONTROL_MAX_BODY_SIZE="${NGINX_CONTROL_MAX_BODY_SIZE:-4k}"
export NGINX_MAP_CACHE_VALID_SECONDS="${NGINX_MAP_CACHE_VALID_SECONDS:-300}"
export NGINX_MAP_CACHE_NOT_FOUND_SECONDS="${NGINX_MAP_CACHE_NOT_FOUND_SECONDS:-30}"
export NGINX_MAP_CACHE_LOCK_TIMEOUT_SECONDS="${NGINX_MAP_CACHE_LOCK_TIMEOUT_SECONDS:-5}"

nginx_variables='${SEVEN_DAYS_HOST} ${SEVEN_DAYS_WEB_PORT}
${NGINX_WORKER_CONNECTIONS} ${NGINX_KEEPALIVE_TIMEOUT_SECONDS}
${NGINX_TRUSTED_PROXY_CIDR} ${NGINX_UPSTREAM_KEEPALIVE}
${NGINX_MAP_CACHE_KEYS_ZONE_SIZE} ${NGINX_MAP_CACHE_MAX_SIZE}
${NGINX_MAP_CACHE_INACTIVE} ${NGINX_MAP_TILE_CACHE_MAX_AGE_SECONDS}
${NGINX_MAP_TILE_STALE_SECONDS} ${NGINX_STATIC_CACHE_MAX_AGE_SECONDS}
${NGINX_BIOME_CACHE_MAX_AGE_SECONDS} ${NGINX_MAP_API_RATE}
${NGINX_PLAYER_API_RATE} ${NGINX_CONTROL_STATUS_RATE}
${NGINX_CONTROL_ACTION_RATE} ${NGINX_MAP_TILE_RATE}
${NGINX_MAP_API_BURST} ${NGINX_PLAYER_API_BURST}
${NGINX_CONTROL_STATUS_BURST} ${NGINX_CONTROL_ACTION_BURST}
${NGINX_MAP_TILE_BURST} ${NGINX_PROXY_CONNECT_TIMEOUT_SECONDS}
${NGINX_MAP_API_READ_TIMEOUT_SECONDS}
${NGINX_PRIVATE_API_READ_TIMEOUT_SECONDS}
${NGINX_MAP_TILE_READ_TIMEOUT_SECONDS} ${NGINX_CONTROL_MAX_BODY_SIZE}
${NGINX_MAP_CACHE_VALID_SECONDS} ${NGINX_MAP_CACHE_NOT_FOUND_SECONDS}
${NGINX_MAP_CACHE_LOCK_TIMEOUT_SECONDS}'

frontend_variables='${FRONTEND_MAP_NATIVE_MAX_ZOOM}
${FRONTEND_MAP_TILE_SIZE} ${FRONTEND_GAME_TIME_REFRESH_MS}
${FRONTEND_PLAYER_REFRESH_MS} ${FRONTEND_ACTIVITY_REFRESH_MS}
${FRONTEND_MAP_ENTITY_REFRESH_MS}
${FRONTEND_TRADER_EXPLORATION_REFRESH_MS}
${FRONTEND_SERVER_VERSION_REFRESH_MS} ${FRONTEND_APP_VERSION_REFRESH_MS}
${FRONTEND_GAME_SCHEDULE_REFRESH_MS}
${FRONTEND_RESTART_STATUS_REFRESH_MS}
${FRONTEND_UNEXPLORED_TILE_MAX_BYTES} ${FRONTEND_TILE_RETRY_DELAYS_MS}
${FRONTEND_CONFIG_RETRY_DELAYS_MS}
${FRONTEND_UNEXPLORED_TILE_REFRESH_MS}
${FRONTEND_MOVING_PLAYER_MIN_SPEED_MPS}
${FRONTEND_MOVING_VEHICLE_MATCH_RADIUS}
${FRONTEND_MOVING_VEHICLE_RELEASE_MS}'

envsubst "$nginx_variables" \
  < /etc/nginx/nginx.conf.template \
  > /tmp/nginx.conf
envsubst "$frontend_variables" \
  < /etc/nginx/frontend-config.js.template \
  > /tmp/frontend-config.js

nginx -t -c /tmp/nginx.conf
exec nginx -c /tmp/nginx.conf -g 'daemon off;'
